# Generated by Django 3.2.5 on 2021-07-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=8000)),
                ('guid', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('pubDate', models.DateField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
